---
apiVersion: v1
kind: Service
metadata:
  name: crawlerservice
  labels:
    app: crawlerservice
spec:
  type: NodePort
  selector:
    app: crawlerservice
  ports:
  - protocol: TCP
    port: 8081
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: crawlerservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: crawlerservice
    spec:
      containers:
      - name: crawlerservice
        image: prashankprince/crawl-web:1.0
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          timeoutSeconds: 1